repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: requirements-txt-fixer
    exclude: ^(.*/)?migrations/

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
    exclude: ^(.*/)?migrations/

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
    exclude: ^(.*/)?migrations/

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
    exclude: ^(.*/)?migrations/
